version: '3'
services:
    onamaeddns:
        ##build: . ## enalbe when debug
        image: hinoshiba/onamaeddns:latest ## comment out when debug.
        tty: true
        volumes:
            - /var/service/onamaeddns/etc/cred:/etc/onamaeddns/cred:ro
        environment:
            - TARGET_DOMAIN=${TARGET_DOMAIN}
            - TARGET_HOST=${TARGET_HOST}
